### ISSUE TITLE
error when run python recognize.py models/output_graph.pb ae_recorded.wav models/alphabet.txt models/lm.binary models/trie

### ISSUE THREAD

**Issue by Vai-bhav** [hiromu/robust_audio_ae#3]
Loading model from file models/output_graph.pb
Traceback (most recent call last):
  File "recognize.py", line 96, in <module>
    main()
  File "recognize.py", line 63, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/home/robust_audio_ae/env/lib/python3.6/site-packages/deepspeech/__init__.py", line 40, in __init__
    status, impl = deepspeech.impl.CreateModel(*args, **kwargs)
TypeError: CreateModel() takes at most 2 arguments (5 given)

**Comment by tom-doerr** [comment]
You could try:
```
pip uninstall deepspeech
pip install deepspeech==0.1.0
```
recognize.py seems to use the deepspeech python package instead of the deepspeech 0.1.0 version you downloaded.
