### ISSUE TITLE
A beginner's confusion

### ISSUE THREAD

**Issue by zhangxin00** [hiromu/robust_audio_ae#5]

**Comment by hiromu** [comment]
I'm sorry but I'm not sure what you referred to as SPT. If you are considering "Sampling Perturbation Technology" proposed by Xiaolei Liu et al. in AAAI 2020, it is not implemented in this repository.
This repository corresponds to our paper titled "Robust Audio Adversarial Example for a Physical Attack" in IJCAI 2019, which proposed a method for generating adversarial examples that can attack in the physical world.
